services:
  - type: web
    name: e-commerce
    runtime: docker
    plan: free
    dockerfile: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "E-Commerce"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        scope: build
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: ecommerce
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
  - type: pserv
    name: e-commerce-db
    runtime: mysql
    plan: free
    versionId: 8
    databaseName: ecommerce
    user: ecommerce
